/**
 * The four columns that exist in Postgres but not in SQLite, computed during
 * the load, inside the transaction, from data the same transaction carries:
 *
 *   articles.content_html            <- renderArticleHtml(...)   [content/render.ts]
 *   article_links.target_article_id  <- resolveLinkTarget(...)
 *   article_search.document,
 *   kb_search.document               <- buildDocument(...)
 *   (article_tags.group_name is GENERATED by Postgres; nothing to derive)
 *
 * All DERIVED, never synced: nothing else may write them, a re-import recomputes
 * them from scratch, and `import_runs.render_version` / `normalize_version`
 * record which code produced what is on disk.
 */
import type { NormalizedText } from "../db/search/normalize.ts";

/**
 * Newline-joins the row's raw text columns in the declared field order
 * (db/search/index.ts ARTICLE_SEARCH_FIELDS / KB_SEARCH_FIELDS) and folds the
 * result. INVARIANT (checked by the database on every row): same length as the
 * raw join — which is what makes `document` slices the folded fields and
 * snippet offsets valid against the raw text.
 */
export function buildDocument(fields: readonly string[]): NormalizedText {
  void fields;
  // TODO normalize(fields.join(DOCUMENT_SEPARATOR))
  throw new Error("not implemented");
}

/**
 * In-library link resolution, once instead of per article read. rm-wenku
 * matched a link two ways (`articles.rs:795-842`): `canonical_url` equality,
 * and the numeric post id in `…/article/{n}` against `source_article_id`. Both
 * reproduced against a Map built while `articles` streamed past — zero queries.
 * Set regardless of the target's status; the read path exposes `articleId` only
 * for a `fetched` target (library/articles.ts), so a status change between
 * imports is reflected without re-deriving.
 */
export interface LinkTargetIndex {
  readonly byCanonicalUrl: ReadonlyMap<string, string>;
  readonly bySourceArticleId: ReadonlyMap<string, string>;
}

export function resolveLinkTarget(index: LinkTargetIndex, url: string): string | null {
  void index;
  void url;
  // TODO index.byCanonicalUrl.get(url) ?? ((m = /\/article\/(\d+)/.exec(url)) ? index.bySourceArticleId.get(m[1]) : null) ?? null
  throw new Error("not implemented");
}
