/**
 * Regenerates src/db/schema.auth.ts from the live Better Auth options. Done in
 * code rather than `npx auth generate` because the CLI trails core (1.4 vs 1.7)
 * and has produced schemas the current adapter rejected. Uses `authOptions()`
 * so the runtime and the schema can never disagree about plugins or fields.
 *
 * Run: `vp run db:schema`, then `vp run db:generate` to diff a migration.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import type { DBFieldAttribute } from "@better-auth/core/db";
import { getSchema } from "better-auth/db";

import { authOptions, type AuthDeps } from "../src/auth.ts";
import { loadConfig } from "../src/config.ts";
import { buildRegistry, RESOURCE_SPECS } from "../src/registry.ts";

const OUT = fileURLToPath(new URL("../src/db/schema.auth.ts", import.meta.url));

/** Only the options object is read; nothing here is ever called. */
function stubDeps(): AuthDeps {
  const config = loadConfig({
    PUBLIC_ORIGIN: "http://localhost:3000",
    AUTH_SECRET: "x".repeat(32),
    DATABASE_URL: "pglite://memory",
    GITHUB_CLIENT_ID: "x",
    GITHUB_CLIENT_SECRET: "x",
    GITHUB_ORG: "x",
  });
  const unreachable = () => {
    throw new Error("schema generation never calls into dependencies");
  };
  return {
    config,
    db: {} as AuthDeps["db"],
    registry: buildRegistry({
      origin: config.PUBLIC_ORIGIN,
      issuer: config.issuer,
      specs: RESOURCE_SPECS,
    }),
    gate: { stampLogin: unreachable, recheck: unreachable, reject: unreachable },
    audit: { record: unreachable, list: unreachable },
    github: { orgMembership: unreachable, profile: unreachable, avatar: unreachable },
    now: () => new Date(),
    onLogin: unreachable,
    fetchClientMetadataResource: unreachable,
  };
}

const schema = getSchema(authOptions(stubDeps()));
const tables = Object.entries(schema)
  .map(([modelName, t]) => ({ modelName, ...t }))
  .sort((a, b) => a.order - b.order);

const imports = new Set(["pgTable", "text"]);
const lines: string[] = [];

function column(field: string, attr: DBFieldAttribute, modelName: string): string {
  const col = attr.fieldName ?? field;
  let expr: string;
  const t = attr.type;
  if (t === "string" || Array.isArray(t)) {
    expr = `text(${JSON.stringify(col)})`;
  } else if (t === "number") {
    if (attr.bigint) {
      imports.add("bigint");
      expr = `bigint(${JSON.stringify(col)}, { mode: "number" })`;
    } else {
      imports.add("integer");
      expr = `integer(${JSON.stringify(col)})`;
    }
  } else if (t === "boolean") {
    imports.add("boolean");
    expr = `boolean(${JSON.stringify(col)})`;
  } else if (t === "date") {
    imports.add("timestamp");
    expr = `timestamp(${JSON.stringify(col)}, { withTimezone: true })`;
  } else if (t === "json") {
    imports.add("jsonb");
    expr = `jsonb(${JSON.stringify(col)})`;
  } else if (t === "string[]") {
    expr = `text(${JSON.stringify(col)}).array()`;
  } else if (t === "number[]") {
    imports.add("integer");
    expr = `integer(${JSON.stringify(col)}).array()`;
  } else {
    throw new Error(`${modelName}.${field}: unsupported type ${String(t)}`);
  }
  if (attr.required) expr += ".notNull()";
  if (attr.unique) expr += ".unique()";
  const dv = attr.defaultValue;
  if (typeof dv === "string" || typeof dv === "number" || typeof dv === "boolean") {
    expr += `.default(${JSON.stringify(dv)})`;
  }
  if (attr.references) {
    imports.add("type AnyPgColumn");
    const target = tables.find((x) => x.modelName === attr.references!.model);
    if (!target)
      throw new Error(`${modelName}.${field}: unknown reference ${attr.references.model}`);
    const onDelete = attr.references.onDelete
      ? `, { onDelete: ${JSON.stringify(attr.references.onDelete)} }`
      : "";
    expr += `.references((): AnyPgColumn => ${attr.references.model}.${attr.references.field}${onDelete})`;
  }
  return `  ${field}: ${expr},`;
}

for (const t of tables) {
  lines.push(`export const ${t.modelName} = pgTable(${JSON.stringify(t.modelName)}, {`);
  lines.push(`  id: text("id").primaryKey(),`);
  for (const [field, attr] of Object.entries(t.fields))
    lines.push(column(field, attr, t.modelName));
  const indexes = (t.indexes ?? []).map((ix) => {
    imports.add(ix.unique ? "uniqueIndex" : "index");
    const cols = ix.columns.map((c) => `t.${c}`).join(", ");
    return `  ${ix.unique ? "uniqueIndex" : "index"}(${JSON.stringify(ix.name)}).on(${cols}),`;
  });
  if (indexes.length > 0) {
    lines.push(`}, (t) => [`, ...indexes, `]);`);
  } else {
    lines.push(`});`);
  }
  lines.push("");
}

const header = `/**
 * GENERATED by scripts/generate-schema.ts (\`vp run db:schema\`) — do not edit.
 * Better Auth ${"1.7.4"} tables for the plugins and fields declared in src/auth.ts.
 * Column names are Better Auth's own so the drizzle adapter needs no mapping.
 */
import { ${[...imports].sort().join(", ")} } from "drizzle-orm/pg-core";

`;
writeFileSync(OUT, header + lines.join("\n"));
console.log(
  `wrote ${tables.length} tables to ${OUT}: ${tables.map((t) => t.modelName).join(", ")}`,
);
